---
- name: crontab
  hosts: dev
  become: true
  tasks:
  - name: Cronjob for logger
    ansible.builtin.cron:
      name: happy
      user: natasha
      minute: "*/2"
      job: 'logger "EX294 exam"'
      state: present
...
