---
- name: Create logical volume as per requirement
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Check if volume group research exists
      ansible.builtin.fail:
        msg: "Volume group does not exist"
      when: ansible_lvm.vgs.research is not defined

    - name: Create logical volume with fallback size
      block:

        - name: Create 1500 MiB logical volume
          community.general.lvol:
            vg: research
            lv: data
            size: 1500m
            state: present

      rescue:

        - name: Display size error message
          ansible.builtin.debug:
            msg: "Could not create logical volume of that size"

        - name: Create 800 MiB logical volume instead
          community.general.lvol:
            vg: research
            lv: data
            size: 800m
            state: present

    - name: Format logical volume with ext4
      community.general.filesystem:
        fstype: ext4
        dev: /dev/research/data
