---
- name: Install packages
  hosts: dev, test, prod
  become: true
 
  tasks:
    - name: php and mariadb packages install
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - php
        - mariadb
    
- name: Install packages
  hosts: dev
  become: true
  
  tasks:    
    - name: RPM tools install
      ansible.builtin.dnf:
        name: '@RPM Development tools'
        state: present
        
- name: Install packages
  hosts: dev
  become: true
 
  tasks:
    - name: upgrede all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
  
...
