---
- name: create a partision
  hosts: all
  become: true
  gather_facts: true
 
  tasks:
    - name: msg
      ansible.builtin.debug:
        msg: "'sdc' in not present"
      when: "'sdc' not in ansible_devices"
    - name: partisiton
      community.general.parted:
        device: /dev/sda
        number: 1
        state: present
        part_end: 1500MiB
      when:
        - "'sda' in ansible_devices"
        - ansible_devices['sda'].size | regex_replace('GB','') | float >= 1.5
 
    - name: partisiton
      community.general.parted:
        device: /dev/sda
        number: 1
        state: present
        part_end: 800MiB
      when:
        - "'sda' in ansible_devices"
        - ansible_devices['sda'].size | regex_replace('GB','') | float < 1.5
 
    - name: partisiton
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 1500MiB
      when:
        - "'sdb' in ansible_devices"
        - ansible_devices['sdb'].size | regex_replace('GB','') | float >= 1.5
 
    - name: partisiton
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 800MiB
      when:
        - "'sdb' in ansible_devices"
        - ansible_devices['sdb'].size | regex_replace('GB','') | float < 1.5
 
    - name: filesystem
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda1
        force: yes
 
    - name: filesystem
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb1
        force: yes
 
    - name: file
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /bbz
        - /bbz1
 
    - name: mount is
      ansible.posix.mount:
        path: /bbz
        src: /dev/sda1
        fstype: ext4
        state: mounted
 
    - name: mount is
      ansible.posix.mount:
        path: /bbz1
        src: /dev/sdb1
        fstype: ext4
        state: mounted
~                                                                                                   
