---
- name: Create partitions based on disk size
  hosts: dev
  become: true
  gather_facts: true
 
  tasks:

    - name: Create 1500MB partition on nvme0n2 (>= 1.5GB)
      community.general.parted:
        device: /dev/nvme0n2
        number: 1
        state: present
        part_end: 1500MiB
      when:
        - "'nvme0n2' in ansible_devices"
        - ansible_devices['nvme0n2'].size | regex_replace('[^0-9.]','') | float >= 1.5
 
    - name: Create 800MB partition on nvme0n2 (< 1.5GB)
      community.general.parted:
        device: /dev/nvme0n2
        number: 1
        state: present
        part_end: 800MiB
      when:
        - "'nvme0n2' in ansible_devices"
        - ansible_devices['nvme0n2'].size | regex_replace('[^0-9.]','') | float < 1.5
 
    - name: Create 1500MB partition on nvme0n3 (>= 1.5GB)
      community.general.parted:
        device: /dev/nvme0n3
        number: 1
        state: present
        part_end: 1500MiB
      when:
        - "'nvme0n3' in ansible_devices"
        - ansible_devices['nvme0n3'].size | regex_replace('[^0-9.]','') | float >= 1.5
 
    - name: Create 800MB partition on nvme0n3 (< 1.5GB)
      community.general.parted:
        device: /dev/nvme0n3
        number: 1
        state: present
        part_end: 800MiB
      when:
        - "'nvme0n3' in ansible_devices"
        - ansible_devices['nvme0n3'].size | regex_replace('[^0-9.]','') | float < 1.5
    - name: Create a ext2 filesystem on nvme0n2
      community.general.filesystem:
        device: /dev/nvme0n2p1
        fstype: ext4
 
    - name: Create a ext2 filesystem on nvme0n2
      community.general.filesystem:
        device: /dev/nvme0n3p1
        fstype: ext4
 
    - name: create mount directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /newpart
        - /newpart1
 
    - name: Mount nvme0n2p1
      ansible.posix.mount:
        path: /newpart
        src: /dev/nvme0n2p1
        fstype: ext4
        state: mounted
 
    - name: Mount nvme0n3p1
      ansible.posix.mount:
        path: /newpart1
        src: /dev/nvme0n3p1
        fstype: ext4
        state: mounted
