---
- name: partition
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: vda missing notice
      ansible.builtin.debug:
        msg: "Disk vda does not exist"
      when: "'vda' not in ansible_devices"

    - name: Create 1500MiB partition if vda >= 1.5GB
      community.general.parted:
        device: /dev/vda
        number: 1
        state: present
        part_end: 1500MiB
      when:
        - "'vda' in ansible_devices"
        - ansible_devices['vda'].size | regex_replace('GB','') | float >= 1.5

    - name: Create 800MiB partition if vda < 1.5GB
      community.general.parted:
        device: /dev/vda
        number: 1
        state: present
        part_end: 800MiB
      when:
        - "'vda' in ansible_devices"
        - ansible_devices['vda'].size | regex_replace('GB','') | float < 1.5

    - name: Create ext4 filesystem
      community.general.filesystem:
        device: /dev/vda1
        fstype: ext4

    - name: Create mount directory
      ansible.builtin.file:
        path: /newpart
        state: directory

    - name: Mount vda1
      ansible.posix.mount:
        path: /newpart
        src: /dev/vda1
        fstype: ext4
        state: mounted
