---
- name: Create web content directory
  hosts: all
  become: true

  tasks:
    - name: Ensure group devops4 exists
      ansible.builtin.group:
        name: devops4
        state: present

    - name: Create /devweb directory
      ansible.builtin.file:
        path: /devweb
        state: directory
        mode: '2775'
        group: devops4
        setype: httpd_sys_content_t

    - name: Copy web content
      ansible.builtin.copy:
        content: "Development"
        dest: /devweb/index.html
        setype: httpd_sys_content_t

    - name: Create symbolic link
      ansible.builtin.file:
        src: /devweb
        dest: /var/www/html/devweb
        state: link
        owner: devops4
        group: devops4
        setype: httpd_sys_content_t

    - name: Permit HTTP traffic in default zone
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
